//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPI_NLH_Alex_Leduc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chambre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chambre()
        {
            this.Lits = new HashSet<Lit>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> Tarif { get; set; }
        public string Type { get; set; }
        public Nullable<int> DepMedID { get; set; }
    
        public virtual DepartementMedical DepartementMedical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lit> Lits { get; set; }
    }
}
