//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPI_NLH_Alex_Leduc
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedView
    {
        public int ID { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public string USR { get; set; }
        public string PSW { get; set; }
        public string NomDept { get; set; }
        public int MedID { get; set; }
        public string NomDeptMed { get; set; }
    }
}
