//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPI_NLH_Alex_Leduc
{
    using System;
    using System.Collections.Generic;
    
    public partial class SejMedView
    {
        public int ID { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int PatientID { get; set; }
        public string NomDeptMed { get; set; }
        public int LitID { get; set; }
        public int MedID { get; set; }
        public System.DateTime DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
    }
}
