//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPI_NLH_Alex_Leduc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NLH_ALEX_LEDUCEntities : DbContext
    {
        public NLH_ALEX_LEDUCEntities()
            : base("name=NLH_ALEX_LEDUCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chambre> Chambres { get; set; }
        public virtual DbSet<Departement> Departements { get; set; }
        public virtual DbSet<DepartementMedical> DepartementMedicals { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<Lit> Lits { get; set; }
        public virtual DbSet<Medecin> Medecins { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Sejour> Sejours { get; set; }
        public virtual DbSet<FullEmpView> FullEmpViews { get; set; }
    }
}
